- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Enable and start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Run pre-requisties
  tags:
  - deployment
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: copy backend conf
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - restart nginx

# - name: restart nginx
#   ansible.builtin.service:
#     name: nginx
#     state: restarted