- name: Installing mysql-server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: Enabling and starting mysql
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Install python mysql dependencies
  ansible.builtin.pip:
    name:
    - PyMySQL
    - cryptography
    executable: pip3.9

- name: Setting up root password
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_password }}"
    login_host: "{{login_host}}"
    filter: version
  ignore_errors: yes
  register: mysql_connection_output

- name: printing the connection output
  ansible.builtin.debug:
    msg: "{{ mysql_connection_output }}"

- name: setting root password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_password }}"
  when: mysql_connection_output.failed is true